apiVersion: v1
kind: Service
metadata:
  name: url-shortener
  labels:
    app: url-shortener   # 👈 זה החלק שחסר
spec:
  selector:
    app: url-shortener
  ports:
    - name: http
      port: 8000
      targetPort: 8000
  type: ClusterIP
