{
 "title": "Url-Shortener-Main-Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Shortens",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 9, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(increase(url_shortened_total[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "P95 Latency",
   "type": "stat",
   "description": "who much time took to 95% of the requests to be completed",
   "gridPos": { "h": 6, "w": 7, "x": 9, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(\n  0.95,\n  sum(rate(http_request_duration_seconds_bucket[5m])) by (le)\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Succses Rate (%)",
   "type": "stat",
   "gridPos": { "h": 6, "w": 7, "x": 16, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(\n  sum(increase(http_requests_total{status!~\"5..\"}[5m]))\n/\n  sum(increase(http_requests_total[5m]))\n) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Redirects",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 9, "x": 0, "y": 6 },
   "targets": [
    {
     "expr": "sum(increase(url_redirect_total[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Error Rate (%)",
   "type": "stat",
   "gridPos": { "h": 6, "w": 7, "x": 9, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(\n  sum(increase(http_requests_total{status=~\"5..\"}[5m]))\n/\n  clamp_min(sum(increase(http_requests_total[5m])), 1)\n) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "URL-Shortener Pods UP",
   "type": "stat",
   "gridPos": { "h": 6, "w": 7, "x": 16, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(up{job=~\".*url-shortener.*\"})",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}